#!/usr/bin/env zsh

set -uo pipefail

while true; do
	find . -type f \( -name '*.ts' -o -name '*.tsx' \) ! -regex '.*/node_modules/.*' ! -regex '.*/dist/.*' ! -regex '.*/static/.*' | \
	entr -srd 'make build && make serve'
done
