#!/usr/bin/env zsh

set -eu pipefail

while true; do
	find . -type f \( -name '*.ts' -o -name '*.tsx' -o -name '*.scss' \) ! -regex '.*/node_modules/.*' ! -regex '.*/dist/.*' | \
	entr make --no-print-directory build
done
